import assert from 'node:assert/strict';
import {test} from 'node:test';
import {importMarkdown,validate,reparent,removeBranch,descendants,visibleTopics,organize} from './src/document.ts';
test('Markdown preserves nested headings and list ancestry',()=>{const d=importMarkdown('# Root\n## Branch\n- Child\n  - Grandchild\n## Other\n- Leaf');const by=(s)=>d.topics.find(n=>n.text===s);assert.equal(by('Child').parentId,by('Branch').id);assert.equal(by('Grandchild').parentId,by('Child').id);assert.equal(by('Leaf').parentId,by('Other').id);validate(d)});
test('skipped headings, plain text and multiple roots remain valid',()=>{for(const md of ['# A\n#### B\n- C','# A\n# B','One\nTwo\nThree']){const d=validate(importMarkdown(md));assert.equal(d.topics.filter(n=>!n.parentId).length,1)}});
test('cycles rejected and branch removal cleans cross links',()=>{let d=importMarkdown('# A\n## B\n- C\n## D');const [a,b,c,e]=d.topics;assert.throws(()=>reparent(d,a.id,c.id));d.links=[{id:'cross',source:c.id,target:e.id}];const removed=removeBranch(d,b.id);assert.equal(removed.topics.length,2);assert.equal(removed.links.length,0);assert.equal(d.topics.length,4);validate(removed)});
test('collapse hides descendants without deleting them',()=>{const d=importMarkdown('# A\n## B\n- C');d.topics[1].collapsed=true;assert.equal(visibleTopics(d).length,2);assert.equal(d.topics.length,3);d.topics[1].collapsed=false;assert.equal(visibleTopics(d).length,3)});
test('drawing and viewport survive JSON roundtrip',()=>{const d=importMarkdown('# A');d.drawings=[{id:'ink',kind:'pen',color:'#333',points:[{x:1,y:2},{x:5,y:8}]}];d.viewport={x:37,y:-85,zoom:.7};assert.equal(JSON.stringify(validate(JSON.parse(JSON.stringify(d)))),JSON.stringify(d));assert.throws(()=>validate({...d,version:99}));assert.throws(()=>validate({...d,links:[{id:'e',source:d.topics[0].id,target:'missing'}]}))});
test('reference load validates and serializes',()=>{const start=performance.now();const d=importMarkdown('# Root\n'+Array.from({length:199},(_,i)=>'## Topic '+i).join('\n'));for(let i=0;i<250;i++)d.links.push({id:'l'+i,source:d.topics[i%199].id,target:d.topics[(i%199)+1].id});for(let i=0;i<100;i++)d.drawings.push({id:'s'+i,kind:'pen',color:'#333',points:Array.from({length:200},(_,j)=>({x:j,y:i+j}))});validate(d);const raw=JSON.stringify(d);validate(JSON.parse(raw));console.log(JSON.stringify({nodes:d.topics.length,links:d.links.length,strokes:d.drawings.length,bytes:raw.length,logicMs:performance.now()-start}));assert.equal(d.topics.length,200)});

