import { useEffect, useMemo, useRef, useState } from 'react';
import { ReactFlow, Background, Controls, Handle, Position, ViewportPortal, useReactFlow, type NodeProps, type Node, type NodeChange } from '@xyflow/react';
import { getStroke } from 'perfect-freehand';
import { descendants, visibleTopics, type Document, type Drawing, type Point, id } from './document';
export type Tool='select'|'hand'|'pen'|'highlight'|'rectangle'|'ellipse'|'arrow'|'text'|'eraser';
type TopicNode=Node<{label:string;color:string;count:number;collapsed:boolean;toggle:()=>void}>;
function TopicView({data,selected}:NodeProps<TopicNode>){return <div className={`topic ${selected?'chosen':''}`} style={{borderColor:data.color}}><Handle type="target" position={Position.Left}/><span>{data.label}</span>{data.count>0&&<button className="nodrag nopan fold" aria-label={data.collapsed?'Expandir ramo':'Recolher ramo'} onClick={e=>{e.stopPropagation();data.toggle()}}>{data.collapsed?`+${data.count}`:'−'}</button>}<Handle type="source" position={Position.Right}/></div>}
const nodeTypes={topic:TopicView};
function Shape({drawing:s}: {drawing:Drawing}){const a=s.points[0],b=s.points.at(-1)!;if(s.kind==='text')return <text x={a.x} y={a.y} fill={s.color} fontSize={22}>{s.text}</text>;
 if(s.kind==='pen'||s.kind==='highlight'){const stroke=getStroke(s.points.map(p=>[p.x,p.y]),{size:s.kind==='highlight'?22:4,thinning:0,smoothing:.6});return <path d={stroke.length?`M ${stroke.map(p=>p.join(',')).join(' L ')} Z`:''} fill={s.color} opacity={s.kind==='highlight'?.3:1}/>}
 const props={stroke:s.color,strokeWidth:3,fill:'none'};if(s.kind==='rectangle')return <rect x={Math.min(a.x,b.x)} y={Math.min(a.y,b.y)} width={Math.abs(b.x-a.x)} height={Math.abs(b.y-a.y)} rx={6} {...props}/>;
 if(s.kind==='ellipse')return <ellipse cx={(a.x+b.x)/2} cy={(a.y+b.y)/2} rx={Math.abs(b.x-a.x)/2} ry={Math.abs(b.y-a.y)/2} {...props}/>;
 const angle=Math.atan2(b.y-a.y,b.x-a.x);return <path d={`M ${a.x} ${a.y} L ${b.x} ${b.y} M ${b.x-15*Math.cos(angle-.5)} ${b.y-15*Math.sin(angle-.5)} L ${b.x} ${b.y} L ${b.x-15*Math.cos(angle+.5)} ${b.y-15*Math.sin(angle+.5)}`} {...props}/>;
}
export function Board({doc,commit,tool,color,selected,onSelect,onEdge,onDrawing,onTopic,fitSignal}:{doc:Document;commit:(d:Document,record?:boolean)=>void;tool:Tool;color:string;selected:string|null;onSelect:(id:string|null)=>void;onEdge:(id:string)=>void;onDrawing:(id:string)=>void;onTopic:(id:string)=>void;fitSignal:number}){
 const flow=useReactFlow();const [draft,setDraft]=useState<Drawing|null>(null);const [moving,setMoving]=useState<Document|null>(null);const gesture=useRef<{doc:Document;origin:Point;root:string}|null>(null);const drawStart=useRef<Point|null>(null);const fingers=useRef(new Map<number,Point>());const pinch=useRef<{distance:number;center:Point;viewport:Document['viewport']}|null>(null);const active=moving??doc;
 const nodes=useMemo(()=>visibleTopics(active).map(n=>({id:n.id,type:'topic',position:n.position,selected:n.id===selected,data:{label:n.text,color:n.color,count:active.topics.filter(c=>c.parentId===n.id).length,collapsed:n.collapsed,toggle:()=>commit({...doc,topics:doc.topics.map(t=>t.id===n.id?{...t,collapsed:!t.collapsed}:t)})}})),[active,selected]);
 const visible=new Set(nodes.map(n=>n.id));const edges=[...active.topics.filter(n=>n.parentId&&visible.has(n.id)&&visible.has(n.parentId)).map(n=>({id:`tree:${n.id}`,source:n.parentId!,target:n.id,style:{stroke:n.color,strokeWidth:2.5},selectable:false})),...active.links.filter(e=>visible.has(e.source)&&visible.has(e.target)).map(e=>({...e,style:{stroke:'#b16f58',strokeWidth:2,strokeDasharray:'6 5'}}))];
 const point=(e:{clientX:number;clientY:number})=>flow.screenToFlowPosition({x:e.clientX,y:e.clientY});
 const drawingMode=!['select','hand','eraser'].includes(tool);
 const lastFit=useRef(fitSignal);useEffect(()=>{if(lastFit.current===fitSignal)return;lastFit.current=fitSignal;void flow.fitView({padding:.25,duration:200})},[fitSignal,flow]);
 return <div className="board" onPointerCancelCapture={()=>{setDraft(null);setMoving(null);gesture.current=null;drawStart.current=null;fingers.current.clear();pinch.current=null}} onPointerDownCapture={e=>{if(e.pointerType!=='touch')return;fingers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(fingers.current.size===2){setDraft(null);const [a,b]=[...fingers.current.values()];pinch.current={distance:Math.max(1,Math.hypot(a.x-b.x,a.y-b.y)),center:{x:(a.x+b.x)/2,y:(a.y+b.y)/2},viewport:flow.getViewport()}}}} onPointerUpCapture={e=>{fingers.current.delete(e.pointerId);if(fingers.current.size===0)pinch.current=null}}>
 <ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} defaultViewport={doc.viewport} minZoom={.15} maxZoom={3} nodesDraggable={tool==='select'} nodesConnectable={tool==='select'} panOnDrag={tool==='hand'||tool==='select'} zoomOnPinch zoomOnScroll deleteKeyCode={null} onMoveEnd={(_,viewport)=>commit({...doc,viewport},false)} onNodeClick={(_,n)=>{onSelect(n.id);onTopic(n.id)}} onPaneClick={()=>onSelect(null)} onEdgeClick={(_,e)=>{if(!e.id.startsWith('tree:'))onEdge(e.id)}} onConnect={c=>{if(c.source!==c.target&&!doc.links.some(e=>e.source===c.source&&e.target===c.target))commit({...doc,links:[...doc.links,{id:id(),source:c.source,target:c.target}]})}}
 onNodeDragStart={(_,n)=>{gesture.current={doc,origin:n.position,root:n.id}}} onNodeDrag={(_,n)=>{const g=gesture.current;if(!g)return;const children=descendants(g.doc,g.root);setMoving({...g.doc,topics:g.doc.topics.map(t=>children.has(t.id)?{...t,position:{x:t.position.x+n.position.x-g.origin.x,y:t.position.y+n.position.y-g.origin.y}}:t)})}} onNodeDragStop={()=>{if(moving)commit(moving);setMoving(null);gesture.current=null}} onNodesChange={(_changes:NodeChange[])=>{}}>
 <Background gap={24} color="#d7d2c6"/><Controls showInteractive={false}/>
 <ViewportPortal><svg className="drawing-world" style={{pointerEvents:tool==='select'||tool==='eraser'?'auto':'none'}}>{doc.drawings.map(s=><g key={s.id} onPointerDown={e=>{if(tool==='eraser'){e.stopPropagation();commit({...doc,drawings:doc.drawings.filter(d=>d.id!==s.id)});return}if(tool==='select'){e.stopPropagation();onDrawing(s.id);drawStart.current=point(e);e.currentTarget.setPointerCapture(e.pointerId)}}} onPointerMove={e=>{if(!drawStart.current||tool!=='select'||!e.buttons)return;const p=point(e),start=drawStart.current;setMoving({...doc,drawings:doc.drawings.map(d=>d.id===s.id?{...d,points:d.points.map(q=>({x:q.x+p.x-start.x,y:q.y+p.y-start.y}))}:d)})}} onPointerUp={()=>{if(moving)commit(moving);setMoving(null);drawStart.current=null}} style={{pointerEvents:tool==='select'||tool==='eraser'?'visiblePainted':'none',cursor:tool==='eraser'?'crosshair':'move'}}><Shape drawing={active.drawings.find(d=>d.id===s.id)??s}/></g>)}{draft&&<Shape drawing={draft}/>}</svg></ViewportPortal>
 </ReactFlow>
 {drawingMode&&<div className="ink-layer" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);if(fingers.current.size>1)return;const p=point(e);if(tool==='text'){const text=window.prompt('Texto da anotação');if(text)commit({...doc,drawings:[...doc.drawings,{id:id(),kind:'text',points:[p],color,text}]});return}setDraft({id:id(),kind:tool as Drawing['kind'],points:[p,p],color})}} onPointerMove={e=>{if(pinch.current&&fingers.current.has(e.pointerId)){fingers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(fingers.current.size<2)return;const [a,b]=[...fingers.current.values()],g=pinch.current;const zoom=Math.min(3,Math.max(.15,g.viewport.zoom*Math.hypot(a.x-b.x,a.y-b.y)/g.distance));const rect=e.currentTarget.getBoundingClientRect();const center={x:(a.x+b.x)/2-rect.left,y:(a.y+b.y)/2-rect.top};const old={x:g.center.x-rect.left,y:g.center.y-rect.top};void flow.setViewport({zoom,x:center.x-(old.x-g.viewport.x)*zoom/g.viewport.zoom,y:center.y-(old.y-g.viewport.y)*zoom/g.viewport.zoom});return}if(draft){const p=point(e);setDraft({...draft,points:tool==='pen'||tool==='highlight'?[...draft.points,p]:[draft.points[0],p]})}}} onPointerUp={()=>{if(draft)commit({...doc,drawings:[...doc.drawings,draft]});else commit({...doc,viewport:flow.getViewport()},false);setDraft(null)}} onPointerCancel={()=>{setDraft(null);fingers.current.clear();pinch.current=null}}/>}
 </div>
}

