import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ReactFlowProvider} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import {Board,type Tool} from './Board';
import {blank,descendants,id,importMarkdown,organize,reparent,removeBranch,validate,type Document} from './document';
import {load,save} from './storage';
import './styles.css';
const tools: [Tool,string][]=[['select','↖ Selecionar'],['hand','✋ Mover'],['pen','✎ Caneta'],['highlight','▰ Marca-texto'],['rectangle','□ Retângulo'],['ellipse','○ Elipse'],['arrow','↗ Seta'],['text','T Texto'],['eraser','⌫ Borracha']];
function App(){
 const [initial]=useState(load);const [docs,setDocs]=useState(initial.docs);const [active,setActive]=useState(initial.docs[0]?.id??'');const [status,setStatus]=useState('');const [message,setMessage]=useState(initial.message);const [sidebar,setSidebar]=useState(false);const [tool,setTool]=useState<Tool>('select');const [color,setColor]=useState('#5969c9');const [selection,setSelection]=useState<string|null>(null);const [edge,setEdge]=useState<string|null>(null);const [drawing,setDrawing]=useState<string|null>(null);const [linkMode,setLinkMode]=useState(false);const [fit,setFit]=useState(0);const [markdown,setMarkdown]=useState<string|null>(null);const [edit,setEdit]=useState<{id:string;text:string}|null>(null);const [parent,setParent]=useState(false);const [deletion,setDeletion]=useState(false);const [blocked,setBlocked]=useState(initial.blocked);const history=useRef(new Map<string,{past:Document[];future:Document[]}>());const file=useRef<HTMLInputElement>(null);
 const doc=docs.find(d=>d.id===active);const topic=doc?.topics.find(n=>n.id===selection);const h=history.current.get(active);
 const commit=(next:Document,record=true)=>{if(!doc||JSON.stringify(next)===JSON.stringify(doc))return;if(record){const stack=history.current.get(active)??{past:[],future:[]};stack.past=[...stack.past.slice(-49),doc];stack.future=[];history.current.set(active,stack)}setDocs(ds=>ds.map(d=>d.id===active?{...next,updatedAt:Date.now()}:d))};
 const persist=()=>{if(blocked){setStatus('É necessário recuperar os dados');return}try{save(docs);setStatus('Salvo neste navegador')}catch{setStatus('Falha ao salvar — exporte um backup')}};
 useEffect(()=>{if(blocked)return;setStatus('Salvando…');const timer=setTimeout(persist,450);return()=>clearTimeout(timer)},[docs,blocked]);
 useEffect(()=>{const flush=()=>{if(!blocked){try{save(docs)}catch{setStatus('Falha ao salvar — exporte um backup')}}};const hidden=()=>{if(document.visibilityState==='hidden')flush()};window.addEventListener('pagehide',flush);document.addEventListener('visibilitychange',hidden);return()=>{window.removeEventListener('pagehide',flush);document.removeEventListener('visibilitychange',hidden)}},[docs,blocked]);
 const choose=(key:string)=>{setActive(key);setSelection(null);setEdge(null);setDrawing(null);setLinkMode(false);setSidebar(false);setEdit(null)};
 const addDoc=(d:Document)=>{setDocs(ds=>[...ds,d]);choose(d.id)};
 const undo=(redo=false)=>{if(!doc)return;const stack=history.current.get(active);if(!stack)return;const from=redo?stack.future:stack.past;const previous=from.pop();if(!previous)return;(redo?stack.past:stack.future).push(doc);commit(previous,false)};
 const add=(parentId?:string)=>{if(!doc)return;const p=doc.topics.find(n=>n.id===parentId);const node={id:id(),text:'Nova ideia',parentId,position:{x:(p?.position.x??0)+300,y:(p?.position.y??0)+doc.topics.filter(n=>n.parentId===parentId).length*130},collapsed:false,color:p?.color??color};commit({...doc,topics:[...doc.topics.map(n=>n.id===parentId?{...n,collapsed:false}:n),node]});setSelection(node.id);setEdit({id:node.id,text:node.text})};
 const exportDoc=()=>{if(!doc)return;const blob=new Blob([JSON.stringify(doc,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${doc.title.replace(/[^\p{L}\p{N} -]/gu,'').slice(0,60)||'mapa'}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 useEffect(()=>{const listener=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();persist()}if((e.ctrlKey||e.metaKey)&&e.key==='z'&&!['INPUT','TEXTAREA'].includes((e.target as HTMLElement).tagName)){e.preventDefault();undo(e.shiftKey)}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener)},[docs,active,blocked]);
 return <div className="shell"><aside className={sidebar?'open':''}><header><b className="wordmark"><span aria-hidden="true">✳</span> mynder</b><button onClick={()=>setSidebar(false)} aria-label="Fechar lista">×</button></header><p>ESPAÇO DE RACIOCÍNIO</p><button className="primary" onClick={()=>addDoc(blank())}>＋ Novo mapa</button><nav>{docs.map(d=><button key={d.id} className={active===d.id?'active':''} onClick={()=>choose(d.id)}>◇ {d.title}</button>)}</nav><footer>Seus mapas ficam neste navegador.<br/>Exporte para levar a outro dispositivo.</footer></aside><main><header className="top"><button onClick={()=>setSidebar(!sidebar)} aria-label="Abrir lista de mapas">☰</button><strong>{doc?.title??'Seus mapas'}</strong><span className={status.startsWith('Falha')?'error':''}>{status}</span><button onClick={persist}>Salvar</button><button onClick={exportDoc} disabled={!doc}>Exportar</button></header>{message&&<div className="notice">{message}<button onClick={()=>setMessage('')}>Fechar</button>{blocked&&<button onClick={()=>{try{localStorage.setItem('rascunho-v2-damaged-copy',localStorage.getItem('rascunho-v2')??'');localStorage.setItem('rascunho-v2',JSON.stringify(docs));setBlocked(false);setMessage('Cópia original preservada; salvamento reativado.')}catch{setMessage('Não foi possível recuperar. Exporte o documento.')}}}>Guardar original e recuperar</button>}</div>}
 <div className="actions"><button onClick={()=>setMarkdown('')}>＋ Texto → mapa</button><button onClick={()=>file.current?.click()}>Importar JSON</button><button onClick={()=>{if(doc){commit(organize(doc));setFit(f=>f+1)}}}>Organizar ramos</button><button onClick={()=>setFit(f=>f+1)}>Ajustar à tela</button><button disabled={!h?.past.length} onClick={()=>undo()}>↶ Desfazer</button><button disabled={!h?.future.length} onClick={()=>undo(true)}>↷ Refazer</button><input hidden ref={file} type="file" accept=".json,application/json" onChange={async e=>{try{const f=e.target.files?.[0];if(!f)return;const d=validate(JSON.parse(await f.text()));addDoc({...d,id:id(),title:`${d.title} (importado)`})}catch(err){setMessage(err instanceof Error?err.message:'Arquivo inválido')}finally{e.target.value=''}}}/></div>
 {doc&&<><ReactFlowProvider key={doc.id}><Board doc={doc} commit={commit} tool={tool} color={color} selected={selection} onSelect={key=>{if(!linkMode)setSelection(key);setEdge(null);setDrawing(null)}} onTopic={target=>{if(linkMode&&selection&&target!==selection){if(!doc.links.some(e=>e.source===selection&&e.target===target))commit({...doc,links:[...doc.links,{id:id(),source:selection,target}]});setLinkMode(false)}}} onEdge={key=>{setEdge(key);setSelection(null);setDrawing(null)}} onDrawing={key=>{setDrawing(key);setSelection(null);setEdge(null)}} fitSignal={fit}/></ReactFlowProvider><div className="tools">{tools.map(([key,label])=><button key={key} className={tool===key?'active':''} onClick={()=>{setTool(key);setLinkMode(false)}}>{label}</button>)}<input type="color" aria-label="Cor da ferramenta" value={color} onChange={e=>setColor(e.target.value)}/><button onClick={()=>add()}>＋ Nó livre</button></div>
 {(topic||edge||drawing)&&<div className="context">{topic?<><b>{topic.text.slice(0,36)}</b><button onClick={()=>setEdit({id:topic.id,text:topic.text})}>Editar</button><button onClick={()=>add(topic.id)}>＋ Filho</button><button onClick={()=>add(topic.parentId)}>＋ Irmão</button><button onClick={()=>{setLinkMode(!linkMode);setTool('select')}}>{linkMode?'Cancelar conexão':'Conectar'}</button><button onClick={()=>setParent(true)}>Mudar pai</button><button onClick={()=>setDeletion(true)}>Apagar ramo</button></>:<><span>{edge?'Conexão selecionada':'Desenho selecionado'}</span><button onClick={()=>{commit({...doc,links:doc.links.filter(e=>e.id!==edge),drawings:doc.drawings.filter(s=>s.id!==drawing)});setEdge(null);setDrawing(null)}}>Apagar</button></>}</div>}{linkMode&&<div className="hint">Toque no nó de destino para criar uma ligação livre.</div>}</>}
 {markdown!==null&&<div className="modal"><section><h2>Das palavras ao mapa</h2><p>Use títulos e listas para definir os ramos. Será criado um novo mapa.</p><textarea aria-label="Texto ou Markdown" value={markdown} onChange={e=>setMarkdown(e.target.value)} placeholder={'# Minha ideia\n## Primeiro ramo\n- Um detalhe'}/><div><button onClick={()=>setMarkdown(null)}>Cancelar</button><button className="primary" onClick={()=>{try{addDoc(importMarkdown(markdown));setMarkdown(null)}catch(e){setMessage((e as Error).message)}}}>Criar mapa</button></div></section></div>}
 {edit&&doc&&<div className="modal"><section><h2>Editar ideia</h2><textarea autoFocus aria-label="Texto da ideia" value={edit.text} onChange={e=>setEdit({...edit,text:e.target.value})}/><div><button onClick={()=>setEdit(null)}>Cancelar</button><button className="primary" onClick={()=>{commit({...doc,title:doc.topics[0]?.id===edit.id?edit.text:doc.title,topics:doc.topics.map(n=>n.id===edit.id?{...n,text:edit.text}:n)});setEdit(null)}}>Aplicar</button></div></section></div>}
 {parent&&topic&&doc&&<div className="modal"><section><h2>Mudar pai de “{topic.text}”</h2><select aria-label="Novo pai" defaultValue={topic.parentId??''} onChange={e=>{try{commit(reparent(doc,topic.id,e.target.value||undefined));setParent(false)}catch(err){setMessage((err as Error).message)}}}><option value="">Sem pai (nó livre)</option>{doc.topics.filter(n=>!descendants(doc,topic.id).has(n.id)).map(n=><option key={n.id} value={n.id}>{n.text}</option>)}</select><button onClick={()=>setParent(false)}>Fechar</button></section></div>}
 {deletion&&topic&&doc&&<div className="modal"><section><h2>Apagar {descendants(doc,topic.id).size} nó(s)?</h2><p>As conexões desses nós também serão removidas. Você poderá desfazer.</p><button onClick={()=>setDeletion(false)}>Cancelar</button><button onClick={()=>{commit(removeBranch(doc,topic.id));setSelection(null);setDeletion(false)}}>Apagar ramo</button></section></div>}
 </main></div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
